# Generated by Django 3.0.5 on 2020-05-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Item ready to be purchase'), ('SOLD', 'Item sold'), ('RESTOCKING', 'Item restocking in few days')], default='SOLD', max_length=10)),
                ('issue', models.CharField(default='No issues', max_length=100)),
            ],
        ),
    ]
